/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EducationSection: typeof import('./src/components/EducationSection.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ExperienceSection: typeof import('./src/components/ExperienceSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PersonalInfoSection: typeof import('./src/components/PersonalInfoSection.vue')['default']
    ResumePDF: typeof import('./src/components/ResumePDF.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillsSection: typeof import('./src/components/SkillsSection.vue')['default']
  }
}
